log stderr all;
router id 10.0.0.254;

protocol device {
    scan time 5;
}

protocol direct {
    ipv4;
}

protocol kernel {
    ipv4 {
        export all;
    };
}

# BGP peers pointing to non-existent hosts
# They will be in Active/Connect states, enough to see protocol output format
protocol bgp peer_as64500 {
    local as 65000;
    neighbor 10.99.0.1 as 64500;
    hold time 30;
    connect retry time 5;
    error wait time 5, 10;
    ipv4 {
        import all;
        export all;
    };
}

protocol bgp peer_as64501 {
    local as 65000;
    neighbor 10.99.0.2 as 64501;
    hold time 30;
    connect retry time 5;
    error wait time 5, 10;
    ipv4 {
        import all;
        export all;
    };
}

protocol bgp peer_as64502 {
    local as 65000;
    neighbor 10.99.0.3 as 64502;
    hold time 30;
    connect retry time 5;
    error wait time 5, 10;
    ipv4 {
        import all;
        export all;
    };
}
